//Given two strings s and t which consist of only lowercase letters.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Find the letter that was added in t.

public class Solution {
    public char findTheDifference(String s, String t) {
        char result = t.charAt(t.length()-1);
        int temp = (int)result;
        
        for (int i = 0; i < s.length(); i++){
            temp = temp ^ (int) s.charAt(i) ^ (int) t.charAt(i);
        }
        
        result = (char) temp;
        return result;
    }
}
